name: flutter_barrage_example
description: An example project for flutter_barrage.

dependencies:
  flutter:
    sdk: flutter
  chewie: ^0.12.1+1

  flutter_barrage:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
